In [2]:
import numpy as np
marks=np.array([88,75,66,99])
marks+5
marks=marks-5
marks/2
print(marks)

marks>=45



[83 70 61 94]


array([ True,  True,  True,  True])

In [3]:
marks=np.array([88,75,66,99])
marks=marks-5
print(marks)

[83 70 61 94]


In [4]:
marks=np.array([88,75,66,99])
marks=marks/5
print(marks)

[17.6 15.  13.2 19.8]


In [5]:
marks=np.array([88,75,66,99])
marks=marks-5
print(marks)

[83 70 61 94]


In [7]:
marks>=83


array([ True, False, False,  True])

In [8]:
marks[-2]

np.int64(61)

Traversing

In [9]:
for i in range(4):
    print(marks[i])

83
70
61
94


In [12]:
marks[:2] # ACADEMIC TEAMS WANT  FIRST2 MARKS

marks[1:4]

array([70, 61, 94])

In [23]:
marks=np.array([
    [85,78,90],
    [92,88,95],
    [76,82,80]
])

In [16]:
print(marks)

[[85 78 90]
 [92 88 95]
 [76 82 80]]


In [ ]:
marks[0,0]

In [ ]:
marks[0][0]

In [21]:
print(marks[1:,0])
print(marks[1:][0])

[92 76]
[92 88 95]


In [24]:
marks[0][0:2]

array([85, 78])

In [25]:
b1=np.array([56,78,89])
b2=np.array([65,76,98])

comb=np.concatenate((b1,b2))
comb

array([56, 78, 89, 65, 76, 98])

In [ ]:
# SPLIT ALWAYS IN EQUAL DIVISON

In [26]:
np.split(comb,2)

[array([56, 78, 89]), array([65, 76, 98])]

In [27]:
print(np.split(comb,2))

[array([56, 78, 89]), array([65, 76, 98])]


In [28]:
np.split(comb,2)

for arr in np.split(comb,2):
    print(arr)

[56 78 89]
[65 76 98]


In [39]:
print(marks[np.where(marks==78)])
print(marks)

ValueError: Calling nonzero on 0d arrays is not allowed. Use np.atleast_1d(scalar).nonzero() instead. If the context of this error is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.

In [33]:
print(np.where(marks>=90))
print(marks)

TypeError: '>=' not supported between instances of 'list' and 'int'

In [40]:
marks=[
    [85,78,90],
    [92,85,98],
    [76,82,80]
]

print(np.where(marks==78))
print(marks)

ValueError: Calling nonzero on 0d arrays is not allowed. Use np.atleast_1d(scalar).nonzero() instead. If the context of this error is of the form `arr[nonzero(cond)]`, just use `arr[cond]`.

In [41]:
mark=np.array([
    [85,78,90],
    [92,85,98],
    [76,82,80]
])

np.where(mark>=80)
print(mark[np.where(mark>=80)])
print(mark)

[85 90 92 85 98 82 80]
[[85 78 90]
 [92 85 98]
 [76 82 80]]


In [43]:
np.sort(mark)[::-1]

array([[76, 80, 82],
       [85, 92, 98],
       [78, 85, 90]])

In [50]:
a=np.array(['ram',45,True])
print(type(a[2]))

<class 'numpy.str_'>
